#pragma config(Motor,  port1,           leftbackmotor, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           leftfrontmotor, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           leftintake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftlift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightlift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightintake,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightbackmotor, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightfrontmotor, tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()//middlelift is the 2 new ones.
{
  // User control code here, inside the loop
int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
  while (true)
  {
   	if(abs(vexRT[Ch3]) > threshold){ // all for mec code says that if joystick value past threshold joystick value = value;
			Y1 = vexRT[Ch3];
		}
		else{
			Y1 = 0;
		}
		if(abs(vexRT[Ch4]) > threshold){ // same as above
			X1 = vexRT[Ch4];
		}
		else{
			X1 = 0;
		}

		if(abs(vexRT[Ch1]) > threshold){ // same as above
			X2 = vexRT[Ch1];
		}
		else{
			X2 = 0;
		}


		//Y1 = ch3 X2 = ch 1 X1 = ch 4
		motor[rightfrontmotor] = Y1 - X2 - X1; // can mess with it, but save this order to go back to in case you mess up.
		motor[rightbackmotor] =  Y1 - X2 + X1;
		motor[leftfrontmotor] = Y1 + X2 + X1;
		motor[leftbackmotor] =  Y1 + X2 - X1;
		// drive train

		// lift
		if(vexRT[Btn5U] == 1)
		{
			motor[leftlift] = motor[rightlift] = 127;

		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[leftlift] = motor[rightlift] = -127;

		}
		else{
			motor[leftlift] = motor[rightlift] =  0;
		}
		//

		//claw
			if(vexRT[Btn6U] == 1)
  	{
			motor[leftintake] = motor[rightintake] = 127;

		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[leftintake] = motor[rightintake] = -127;

		}
		else{
			motor[leftintake] = motor[rightintake] =  0;
		}
		//
		wait1Msec(50);
  }
}
